export { default as SignIn } from './SingIn';
export { default as SignUp } from './SignUp';
export { default as ForgotPassword } from './ForgotPassword';
export { default as Home } from './Home';
export { default as Profile } from './Profile';
export { default as Modules } from './Modules';
export { default as Notifications } from './Notifications';
export { default as Module } from './Modules/Module';
export { default as Lesson } from './Modules/Module/Lesson';
